name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/merge-link:latest
    
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/merge-link
  
  arm-build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: uraimo/run-on-arch-action@v2.1.1
      name: ARM builder
      id: build
      with:
        arch: aarch64
        distro: bullseye
        dependencies: |
          apt update && apt install apt-transport-https ca-certificates curl gnupg lsb-release -y
        
        add-repo: |
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

        cfg-repo: |
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \ $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        install: |
          apt update && apt -y install docker-ce docker-ce-cli containerd.io
        
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} && docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/merge-link-arm:latest && docker push ${{secrets.DOCKER_USER}}/merge-link-arm

    - name: Get the output
      run: |
        echo "${{ steps.build.outputs }}"
